// A very simple approach, with a predefined maximum number of ayahs per surah.
// This might not be accurate for all surahs, so you may want to adjust this or use a more detailed approach.
const SURAH_AYAH_COUNTS : number[] = [
  7,   // Al-Fatihah
  286, // Al-Baqarah
  200, // Aal-E-Imran
  176, // An-Nisa'
  120, // Al-Ma'idah
  165, // Al-An'am
  206, // Al-A'raf
  75,  // Al-Anfal
  129, // At-Tawbah
  109, // Yunus
  123, // Hud
  111, // Yusuf
  43,  // Ar-Ra'd
  52,  // Ibrahim
  99,  // Al-Hijr
  128, // An-Nahl
  111, // Al-Isra
  110, // Al-Kahf
  98,  // Maryam
  135, // Ta-Ha
  112, // Al-Anbiya
  78,  // Al-Haj
  118, // Al-Mu'minun
  64,  // Az-Zumar
  77,  // Al-Furqan
  227, // Ash-Shu'ara
  93,  // An-Naml
  88,  // Al-Qasas
  69,  // Al-Ankabut
  60,  // Ar-Rum
  34,  // Luqman
  30,  // As-Sajda
  73,  // Al-Ahzab
  54,  // Saba
  45,  // Fatir
  83,  // Ya-Sin
  182, // As-Saffat
  88,  // Sad
  75,  // Az-Zumar
  85,  // Ghafir
  54,  // Fussilat
  53,  // Ash-Shura
  89,  // Az-Zukhruf
  59,  // Ad-Dukhan
  37,  // Al-Jathiya
  35,  // Al-Ahqaf
  38,  // Muhammad
  29,  // Al-Fath
  18,  // Al-Hujurat
  45,  // Qaf
  60,  // Adh-Dhariyat
  49,  // At-Tur
  62,  // An-Najm
  55,  // Al-Qamar
  78,  // Ar-Rahman
  96,  // Al-Waqi'a
  29,  // Al-Hadid
  22,  // Al-Mujadila
  24,  // Al-Hashr
  13,  // Al-Mumtahina
  14,  // As-Saff
  11,  // Al-Jumu'a
  11,  // Al-Munafiqun
  18,  // At-Taghabun
  12,  // At-Talaq
  12,  // At-Tahrim
  30,  // Al-Mulk
  52,  // Al-Qalam
  52,  // Al-Haaqqa
  44,  // Al-Ma'arij
  28,  // Nuh
  28,  // Al-Jinn
  20,  // Al-Muzzammil
  56,  // Al-Muddathir
  40,  // Qiyama
  31,  // Al-Insan
  50,  // Al-Mursalat
  40,  // An-Naba
  46,  // An-Nazi'at
  42,  // Abasa
  29,  // At-Takwir
  19,  // Al-Infitar
  36,  // Al-Mutaffifin
  25,  // Al-Inshiqaq
  22,  // Al-Burooj
  17,  // At-Tariq
  19,  // Al-Ala
  26,  // Al-Ghashiya
  30,  // Al-Fajr
  20,  // Al-Balad
  15,  // Ash-Shams
  21,  // Al-Layl
  11,  // Ad-Duhaa
  8,   // Al-Inshirah
  8,   // At-Tin
  19,  // Al-Alaq
  5,   // Al-Qadr
  8,   // Al-Bayyina
  8,   // Az-Zalzalah
  11,  // Al-Adiyat
  11,  // Al-Qari'a
  8,   // At-Takathur
  3,   // Al-Asr
  9,   // Al-Humaza
  5,   // Al-Fil
  4,   // Quraish
  7,   // Al-Ma'un
  3,   // Al-Kawthar
  6,   // Al-Kafiroon
  3,   // An-Nasr
  5,   // Al-Masadd
  4,   // Al-Ikhlas
  5,   // Al-Falaq
  6    // An-Nas
];

export { SURAH_AYAH_COUNTS }